import jsPDF from "jspdf";

export const generateReport = (data) => {
    const doc = new jsPDF();

    const {
        filename,
        ats_score,
        matching_skills,
        missing_skills,
        strengths,
        improvements,
        recommendations,
    } = data;

    let y = 20;

    // Title
    doc.setFontSize(20);
    doc.text("AI Resume Coach Report", 20, y);

    y += 15;

    doc.setFontSize(12);

    doc.text(`Resume: ${filename}`, 20, y);

    y += 10;

    doc.text(`ATS Match Score: ${ats_score}%`, 20, y);

    y += 15;

    // Strengths
    doc.setFontSize(14);
    doc.text("Strengths", 20, y);

    y += 10;

    doc.setFontSize(12);

    strengths.forEach((item) => {
        doc.text(`• ${item}`, 25, y);
        y += 8;
    });

    y += 5;

    // Improvements
    doc.setFontSize(14);
    doc.text("Areas of Improvement", 20, y);

    y += 10;

    doc.setFontSize(12);

    improvements.forEach((item) => {
        doc.text(`• ${item}`, 25, y);
        y += 8;
    });

    y += 5;

    // Matching Skills
    doc.setFontSize(14);
    doc.text("Matching Skills", 20, y);

    y += 10;

    doc.setFontSize(12);

    matching_skills.forEach((skill) => {
        doc.text(`✓ ${skill}`, 25, y);
        y += 8;
    });

    y += 5;

    // Missing Skills
    doc.setFontSize(14);
    doc.text("Missing Skills", 20, y);

    y += 10;

    doc.setFontSize(12);

    missing_skills.forEach((skill) => {
        doc.text(`✗ ${skill}`, 25, y);
        y += 8;
    });

    y += 5;

    // Course Recommendations
    doc.setFontSize(14);
    doc.text("Free Learning Recommendations", 20, y);

    y += 10;

    doc.setFontSize(12);

    recommendations.forEach((course) => {
        doc.text(
            `${course.skill}: ${course.course}`,
            25,
            y
        );

        y += 8;

        doc.text(
            `${course.link}`,
            30,
            y
        );

        y += 10;
    });

    y += 10;

    doc.setFontSize(10);

    doc.text(
        `Generated on: ${new Date().toLocaleString()}`,
        20,
        y
    );

    y += 8;

    doc.text(
        "Generated by AI Resume Coach",
        20,
        y
    );

    doc.save("AI_Resume_Coach_Report.pdf");
};